executors:
  deploy:
    docker:
    - {image: kroniak/ssh-client}
    environment: {DISTRO: << parameters.dist >>}
    parameters:
      dist: {type: string}
    working_directory: /output
  rpmbuilder:
    docker:
    - {image: 'getpagespeed/rpmbuilder:<< parameters.dist >>'}
    environment: {RPMLINT: << parameters.rpmlint >>}
    parameters:
      dist: {type: string}
      rpmlint: {default: 1, type: integer}
    working_directory: /sources
jobs:
  build:
    executor: {dist: << parameters.dist >>, name: rpmbuilder}
    parameters:
      dist: {type: string}
    steps:
    - checkout
    - run: {command: build, name: 'Run the build itself: this will do rpmlint and
          check RPMs existence among other things.'}
    - persist_to_workspace:
        paths: ['*.rpm']
        root: /output
  deploy:
    executor: {dist: << parameters.dist >>, name: deploy}
    parameters:
      dist: {description: The dist tag of OS to deploy for, type: string}
    steps:
    - attach_workspace: {at: /output}
    - add_ssh_keys:
        fingerprints: ['8c:a4:dd:2c:47:4c:63:aa:90:0b:e0:d6:15:be:87:82']
version: 2.1
workflows:
  build-deploy-amzn2:
  - build:
      dist: amzn2
  - deploy:
      context: org-global
      dist: amzn2
      name: deploy-amzn2
