defaults: &defaults
    environment:
      RPMLINT: 1
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: "Run the build itself: this will do rpmlint and check RPMs existence among other things."
          command: build
      - persist_to_workspace:
          root: /output
          paths:
            - "*.rpm"

version: 2 
jobs: # a collection of steps
  el6:
    docker: # run the steps with Docker
      - image: getpagespeed/rpmbuilder:centos-6
    working_directory: /sources # directory where steps will run
    <<: *defaults
  el7:
    docker:
      - image: getpagespeed/rpmbuilder:centos-7
    working_directory: /sources # directory where steps will run
    <<: *defaults
  deploy:
    docker:
      - image: centos:7
    environment:
      RPMLINT: 1
    working_directory: /output
    steps:
      - attach_workspace:
          at: /output
      - add_ssh_keys:
          fingerprints:
            - "8c:a4:dd:2c:47:4c:63:aa:90:0b:e0:d6:15:be:87:82"
      - run:
          name: "Install stuff to deploy"
          command: yum -y install openssh-clients
      - run:
          name: "Ensure project specific upload directory to avoid deploy collisions"
          command: ssh -o StrictHostKeyChecking=no $GPS_BUILD_USER@$GPS_BUILD_SERVER "mkdir -p ~/incoming/$CIRCLE_PROJECT_REPONAME"
      - run:
          name: "Deploy all RPMs to GetPageSpeed repo."
          command: scp -o StrictHostKeyChecking=no -q -r *.rpm $GPS_BUILD_USER@$GPS_BUILD_SERVER:~/incoming/$CIRCLE_PROJECT_REPONAME/
      - run:
          name: "Trigger Deploy Hook."
          command: ssh -o StrictHostKeyChecking=no -q $GPS_BUILD_USER@$GPS_BUILD_SERVER "nohup ~/scripts/incoming.sh $CIRCLE_PROJECT_REPONAME > ~/incoming/$CIRCLE_PROJECT_REPONAME/process.log 2>&1&"
workflows:
  version: 2
  build-deploy:
    jobs:
      - el6
      - el7
      - deploy:
          context: org-global
          requires:
            - el6
            - el7
          filters:
            branches:
              only: master
